### ISSUE TITLE
Todo List 

### ISSUE THREAD

**Issue by Kucukaslan** [Kucukaslan/cs342_pj_03#2]
### Required methods:
- [x] int dma_init (int m);
- [x] void *dma_alloc (int size);
- [x] void dma_free (void *p);
- [x] void dma_print_page(int pno);
- [x] void dma_print_bitmap();
- [x] void dma_print_blocks();
- [x] format "dma_print_blocks"'s output
- [x] int dma_give_intfrag();  
  
### Additional methods:
- [x] void word_to_binary( unsigned long int num, char *binary);
- [x] unsigned long int word_manipulator(int is_new_allocation, int start, int size);
- [x] those ul things

## Part B [Docs link](https://docs.google.com/document/d/1_zWnMsEXYqgq9-26IPSvL-m4e49e8xNYig-hE53tdFA/edit?usp=sharing)
- [x] obtain data
- [x] draw the graphs
- [x] write the report

## Submission
- [x] submit the code
- [x] review the submission
